export default {
  id: "perplexity-web",
  priority: 220,
  alias: "perplexity-web",
  aliases: [
    "pw",
  ],
  uiAlias: "pw",
  display: {
    name: "Perplexity Web (Pro/Max)",
    icon: "search",
    color: "#20808D",
    textIcon: "PW",
    website: "https://www.perplexity.ai",
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste your __Secure-next-auth.session-token cookie value from perplexity.ai",
  transport: {
    baseUrl: "https://www.perplexity.ai/rest/sse/perplexity_ask",
    format: "perplexity-web",
    authType: "cookie",
  },
  models: [
    { id: "pplx-auto", name: "Perplexity Auto (Free)" },
    { id: "pplx-best", name: "Perplexity Best (turbo)" },
    { id: "pplx-sonar", name: "Sonar 2" },
    { id: "pplx-gpt", name: "GPT-5.5 (via Perplexity)" },
    { id: "pplx-gpt56", name: "GPT-5.6 Sol (via Perplexity)" },
    { id: "pplx-gpt6", name: "GPT-6.1 Sol (via Perplexity)" },
    { id: "pplx-sonnet", name: "Claude Sonnet 5.5 (via Perplexity)" },
    { id: "pplx-opus", name: "Claude Opus 5.5 (via Perplexity)" },
    { id: "pplx-haiku", name: "Claude Haiku 5.5 (via Perplexity)" },
    { id: "pplx-fable", name: "Claude Fable 5.1 (via Perplexity)" },
    { id: "pplx-gemini", name: "Gemini 3.8 Flash (via Perplexity)" },
    { id: "pplx-gemini-pro", name: "Gemini 3.1 Pro (via Perplexity)" },
    { id: "pplx-grok", name: "Grok 4.7 (via Perplexity)" },
    { id: "pplx-nemotron", name: "Nemotron 3 Ultra (via Perplexity)" },
    { id: "pplx-kimi", name: "Kimi K3 (via Perplexity)" },
    { id: "pplx-glm", name: "GLM-5.3 (via Perplexity)" },
  ],
};
